### Detect Trash (IoT ESP32 hit)
### Replace the qr_code with the actual UUID of the trash bin and the image with an actual image path
POST http://127.0.0.1:8000/iot/detect
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="qr_code"

3416cb3a-c4f5-4c39-8fb9-f5925e3f0efb
--boundary
Content-Disposition: form-data; name="image"; filename="sample_trash.jpg"
Content-Type: image/jpeg

< ./roblox.png
--boundary--

