### Get Point Earned Today
GET http://127.0.0.1:8000/history/point-earned
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzc1NTQzMzM4LCJ0eXBlIjoiYWNjZXNzIn0.a61tHMz6EZhg3VXju9xuKGq0aEeA-p0AMXLXeTt6sz4

