### Refresh Access Token
POST http://127.0.0.1:8000/auth/refresh-token
Content-Type: application/json
Accept: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzc1NjEyNjc3LCJ0eXBlIjoicmVmcmVzaCJ9.YaRGeGYW8DX7a5CMUY9MjGIf-970V1zQL2JMRLIaclU"
}

