### Login
POST http://127.0.0.1:8000/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "reset_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzQ4NDYzOTAsInR5cGUiOiJyZXNldF9wYXNzd29yZCIsImVtYWlsIjoid2lsZGFuMjczNzBAZ21haWwuY29tIn0.QX_3mhX8_63MaaI3kizSiNowsPE3SAbAMWP8UOdE5FM",
  "new_password": "123123123",
  "password_confirmation": "123123123"
}