### Update User Profile (Form Data & File Upload)
POST http://127.0.0.1:8000/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzc1MDI3NDcyLCJ0eXBlIjoiYWNjZXNzIn0.be02CtkqsYRaI7L8qUUgnZVoosxRok_gWChUdgWA2VE
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="full_name"

Nama Perubahan
--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="new_avatar.jpg"
Content-Type: image/jpeg

< ./roblox.png
--WebAppBoundary--
