### Verify Otp
POST http://127.0.0.1:8000/auth/verify
Content-Type: application/json
Accept: application/json

{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzQ4NDU3MzUsInR5cGUiOiJmb3Jnb3RfcGFzc3dvcmQiLCJlbWFpbCI6IndpbGRhbjI3MzcwQGdtYWlsLmNvbSIsIm90cF9jb2RlIjoiMjk4OTk0In0.69ickVrUH9zq371fewxuenHtHqAxKVYMVbj7fjUMyWk",
  "otp_code": "298994"
}