### Verify Otp
POST http://127.0.0.1:8000/auth/verify
Content-Type: application/json
Accept: application/json

{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzQ4MzY4ODgsInR5cGUiOiJyZWdpc3RyYXRpb24iLCJlbWFpbCI6IndpbGRhbjI3MzcwQGdtYWlsLmNvbSIsIm90cF9jb2RlIjoiNTAxNDI1In0.BK0knEUhASEWz7QNlX49hCNQBhz_kWIUDD4_15_HIdg",
  "otp_code": "501425"
}