"""update_email_verified_at_column

Revision ID: 09e3dc1e7454
Revises: 476d3118197e
Create Date: 2026-03-28 16:01:35.337694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e3dc1e7454'
down_revision: Union[str, Sequence[str], None] = '476d3118197e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'verified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified_at', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'email_verified_at')
    # ### end Alembic commands ###
