"""add last_activity_at to bin_session

Revision ID: 1143e9ade33a
Revises: 9a25f6bd1088
Create Date: 2026-04-06 09:53:17.098580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1143e9ade33a'
down_revision: Union[str, Sequence[str], None] = '9a25f6bd1088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bin_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bin_sessions', schema=None) as batch_op:
        batch_op.drop_column('last_activity_at')

    # ### end Alembic commands ###
