"""Initial schema

Revision ID: 3486a5cbe591
Revises: 
Create Date: 2026-04-15 10:31:47.708933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3486a5cbe591'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trash_bins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('capacity_organic', sa.Integer(), nullable=True),
    sa.Column('capacity_inorganic', sa.Integer(), nullable=True),
    sa.Column('capacity_b3', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trash_bins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trash_bins_qr_code'), ['qr_code'], unique=True)

    op.create_table('trash_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compartment_type', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trash_bin_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trash_bin_id'], ['trash_bins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bin_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bin_sessions_trash_bin_id'), ['trash_bin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bin_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('disposal_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trash_bin_id', sa.Integer(), nullable=False),
    sa.Column('trash_category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trash_bin_id'], ['trash_bins.id'], ),
    sa.ForeignKeyConstraint(['trash_category_id'], ['trash_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disposal_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disposal_histories_trash_bin_id'), ['trash_bin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disposal_histories_trash_category_id'), ['trash_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disposal_histories_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token'), ['refresh_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('disposal_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disposal_histories_user_id'))
        batch_op.drop_index(batch_op.f('ix_disposal_histories_trash_category_id'))
        batch_op.drop_index(batch_op.f('ix_disposal_histories_trash_bin_id'))

    op.drop_table('disposal_histories')
    with op.batch_alter_table('bin_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bin_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_bin_sessions_trash_bin_id'))

    op.drop_table('bin_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('trash_categories')
    with op.batch_alter_table('trash_bins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trash_bins_qr_code'))

    op.drop_table('trash_bins')
    # ### end Alembic commands ###
