"""add total_points and total_items to bin_sessions

Revision ID: 9a25f6bd1088
Revises: ba608d2a1e41
Create Date: 2026-04-06 09:23:59.024017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a25f6bd1088'
down_revision: Union[str, Sequence[str], None] = 'ba608d2a1e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bin_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_items', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bin_sessions', schema=None) as batch_op:
        batch_op.drop_column('total_items')
        batch_op.drop_column('total_points')

    # ### end Alembic commands ###
